package com.example.data

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.withContext

class Repository(private val db: AppDatabase) {

    private val productDao = db.productDao()
    private val cartDao = db.cartDao()
    private val wishlistDao = db.wishlistDao()
    private val addressDao = db.addressDao()
    private val orderDao = db.orderDao()
    private val couponDao = db.couponDao()
    private val reviewDao = db.reviewDao()
    private val profileDao = db.profileDao()

    // Seed data on launch if database is empty
    suspend fun seedDatabaseIfEmpty() {
        withContext(Dispatchers.IO) {
            val count = productDao.getProductCount()
            if (count == 0) {
                // Seed Products
                val products = SampleData.getSampleProducts()
                productDao.insertProducts(products)

                // Seed Coupons
                val coupons = SampleData.getSampleCoupons()
                couponDao.insertCoupons(coupons)

                // Seed Addresses
                val addresses = SampleData.getDefaultAddresses()
                for (address in addresses) {
                    addressDao.insertAddress(address)
                }

                // Seed Profile
                val profile = SampleData.getInitialProfile()
                profileDao.insertProfile(profile)

                // Seed Reviews for seeded products
                // To support Room autogenerated IDs, we assume ids 1 to 32
                for (pId in 1..32) {
                    val reviews = SampleData.getSampleReviews(pId)
                    for (review in reviews) {
                        reviewDao.insertReview(review)
                    }
                }
            }
        }
    }

    // Products
    fun getAllProducts(): Flow<List<Product>> = productDao.getAllProducts()
    fun getProductById(id: Int): Flow<Product?> = productDao.getProductById(id)

    // Cart
    fun getCartItems(): Flow<List<CartItem>> = cartDao.getCartItems()
    suspend fun addToCart(productId: Int, color: String, size: String, qty: Int) {
        withContext(Dispatchers.IO) {
            val currentItems = cartDao.getCartItems().firstOrNull() ?: emptyList()
            val existing = currentItems.find {
                it.productId == productId && it.colorName == color && it.selectedSize == size
            }
            if (existing != null) {
                cartDao.updateCartQuantity(existing.id, existing.quantity + qty)
            } else {
                cartDao.insertCartItem(
                    CartItem(
                        productId = productId,
                        colorName = color,
                        selectedSize = size,
                        quantity = qty
                    )
                )
            }
        }
    }
    suspend fun updateCartQty(id: Int, quantity: Int) {
        withContext(Dispatchers.IO) {
            if (quantity <= 0) {
                cartDao.deleteCartItem(id)
            } else {
                cartDao.updateCartQuantity(id, quantity)
            }
        }
    }
    suspend fun removeFromCart(id: Int) {
        withContext(Dispatchers.IO) {
            cartDao.deleteCartItem(id)
        }
    }
    suspend fun clearCart() {
        withContext(Dispatchers.IO) {
            cartDao.clearCart()
        }
    }

    // Wishlist
    fun getWishlistItems(): Flow<List<WishlistItem>> = wishlistDao.getWishlistItems()
    suspend fun toggleWishlist(productId: Int) {
        withContext(Dispatchers.IO) {
            val current = wishlistDao.getWishlistItems().firstOrNull() ?: emptyList()
            if (current.any { it.productId == productId }) {
                wishlistDao.deleteWishlistItem(productId)
            } else {
                wishlistDao.insertWishlistItem(WishlistItem(productId))
            }
        }
    }
    fun isWishlisted(productId: Int): Flow<Boolean> = wishlistDao.isWishlisted(productId)

    // Addresses
    fun getAddresses(): Flow<List<UserAddress>> = addressDao.getAddresses()
    suspend fun addAddress(address: UserAddress) {
        withContext(Dispatchers.IO) {
            if (address.isDefault) {
                addressDao.clearDefaultAddresses()
            }
            addressDao.insertAddress(address)
        }
    }
    suspend fun deleteAddress(id: Int) {
        withContext(Dispatchers.IO) {
            addressDao.deleteAddress(id)
        }
    }
    suspend fun setAddressAsDefault(id: Int) {
        withContext(Dispatchers.IO) {
            addressDao.setAsDefault(id)
        }
    }

    // Orders
    fun getOrders(): Flow<List<Order>> = orderDao.getOrders()
    fun getOrderById(id: Int): Flow<Order?> = orderDao.getOrderById(id)
    suspend fun placeOrder(order: Order): Long {
        return withContext(Dispatchers.IO) {
            orderDao.insertOrder(order)
        }
    }
    suspend fun cancelOrder(id: Int) {
        withContext(Dispatchers.IO) {
            orderDao.updateOrderStatus(id, "Cancelled")
        }
    }

    // Coupons
    fun getCoupons(): Flow<List<Coupon>> = couponDao.getCoupons()
    suspend fun getCouponByCode(code: String): Coupon? {
        return withContext(Dispatchers.IO) {
            couponDao.getCouponByCode(code)
        }
    }

    // Reviews
    fun getReviewsForProduct(productId: Int): Flow<List<Review>> = reviewDao.getReviewsForProduct(productId)
    suspend fun addReview(review: Review) {
        withContext(Dispatchers.IO) {
            reviewDao.insertReview(review)
        }
    }

    // Profile
    fun getProfile(): Flow<UserProfile?> = profileDao.getProfile()
    suspend fun updateProfile(profile: UserProfile) {
        withContext(Dispatchers.IO) {
            profileDao.insertProfile(profile)
        }
    }
}
